# Generated by Django 5.0.3 on 2024-04-24 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AllocationAdmin', '0002_alter_event_code_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='event',
        ),
    ]
